package com.mobile.petra.router

sealed class Routes(val route: String) {

    object Home : Routes("home")
    object Details : Routes("details")
    object Onboarding1 : Routes("onboarding1")
    object Onboarding2 : Routes("onboarding2")
    object Onboarding3 : Routes("onboarding3")
    object Onboarding4 : Routes("onboarding4")
    object SwipeScreen : Routes("swipe_screen")
    object Login : Routes("login")
    object EnterPhoneNumber : Routes("input_phone_number")
    object VerifyPhoneNumber : Routes("verify_phone_number")
    object ResetPin : Routes(route = "reset_pin_code")
    object ResetPinOTP : Routes(route = "reset_otp_pin_code")
    object CreateAccount: Routes(route = "create_account")
    object NavigateLiveness: Routes(route = "NavigateLiveness")
    object PicturePreview: Routes(route = "PicturePreview")
    object BiometricAccessEnabledDialog: Routes(route = "biometric_enabled_dialog")
    object CreateAccountCompleteProfile: Routes(route = "create_account_complete_profile")
    object SetPinCode : Routes(route = "set_pin_code")
    object RevampedSetPinCode : Routes(route = "revamped_set_pin_code")
    object ConfirmPinCode : Routes(route = "confirm_pin_code")
    object RevampedConfirmPinCode : Routes(route = "revamped_confirm_pin_code")
    object EnableBiometric : Routes(route = "enable_biometric")
    object CheckMarkDialog : Routes(route = "check_mark_dialog")
    object WalletCreationSuccessful : Routes(route = "wallet_creation_successful")
    object FundTransferOptions: Routes(route = "transfer_options")
    object KegowTransfer: Routes(route = "kegow_transfer")
    object Beneficiaries: Routes(route = "beneficiaries")
    object TransferSuccessful: Routes(route = "kegow_transfer_successful")
    object TransferProcessing: Routes(route = "transfer_processing")
    object SelectRecipientBank: Routes(route = "choose_bank")
    object BankTransfer: Routes(route = "bank_transfer")
    object BankSuccessful: Routes(route = "bank_successful")
    object Dashboard: Routes(route = "dashboard")
    object FundWalletBankTransfer: Routes(route = "fund_wallet_bank_transfer")
    object FundWalletCashDeposit: Routes(route = "fund_wallet_cash_deposit")
    object FundWalletScanQRCode: Routes(route = "fund_wallet_scan_qr_code")
    object Airtime:Routes("Airtime")
    object AirtimeSuccessfulPrompt:Routes("airtime_successful_screen")
    object Data:Routes("data")
    object DataSuccessfulScreen:Routes("data_successful_screen")
    object DataFailedScreen:Routes("data_failed_screen")
    object BillsHomepage: Routes("BillsHomePage")
    object Electricity: Routes("electricity")
    object ElectricityBillSuccessful: Routes(route = "electricity_successful")
    object CableTV: Routes("cable_tv")
    object CableTVSuccessful: Routes("cable_tv_successful")
    object Internet: Routes("internet")
    object AccountDetails: Routes("user_details")
    object ChangeEmail: Routes("change_email")
    object NewEmail: Routes("new_email")
    object WelcomeScreen: Routes("welcome_screen")
    object AddEmailSuccessfulDialog: Routes("add_email_successful_dialog")
    object TierUpgradeSelection: Routes("tier_upgrade_selection")
    object Tier2UpgradeSelection: Routes("tier_2_upgrade_selection")
    object Tier3UpgradeSelection: Routes("tier_3_upgrade_selection")
    object Tier2IdentificationCard: Routes("tier_2_upgrade_user_id_card")
    object UploadIDSuccessful: Routes("id_upload_successful")
    object Tier3UpgradeUtilityBill: Routes("tier_3_upgrade_utility_bill")
    object UploadUtilityBillSuccessful: Routes("utility_bill_upload_successful")
    object RestrictAccount: Routes("restrict_account")
    object RestrictAccountPinInput: Routes("restrict_account_pin")
    object RestrictAccountPrompt: Routes("restrict_account_prompt")
    object Support: Routes("support")
    object GiveUsACall: Routes("give_us_a_call")
    object ChatWithUs: Routes("chat_with_us")
    object EmailUs: Routes("email_us")
    object FAQs: Routes("faqs")
    object CardsAndBanks: Routes("card_and_bank")
    object StatementAndReport: Routes("statement_and_report")
    object StatementAndReportSent: Routes("statement_and_report_sent")
    object SecuritySettings: Routes("security_settings")
    object ChangePIN: Routes("change_pin")
    object ChangePINSuccessfulPrompt: Routes("change_pin_successful")
    object SecurityQuestionsAuth: Routes("security_settings_auth")
    object SecurityQuestions: Routes("security_questions")
    object SecurityQuestionAddSuccessfulDialog: Routes("security_settings_successful_dialog")
    object Notification: Routes("notification")
    object AppTransactionsNotification: Routes("app_notifications")
    object Referrals: Routes("referrals")
    object PersonalDetail: Routes("personal_detail")
    object AdditionalPersonalDetail: Routes("additional_personal detail")
    object VerificationTypeSelection: Routes("verification_type_selection")
    object TermsAndConditions: Routes("terms_and_condition")
    object SavingsHomepage: Routes("savings_homepage")
    object TargetSavingsOnboarding: Routes("target_savings_onboarding")
    object CreateTargetSavings: Routes("create_target_savings")
    object TargetSavingsCreationSuccessful: Routes("target_savings_created")
    object TargetSavingsCreationFailed: Routes("target_savings_not_created")
    object TargetSavingsProgressDashboard: Routes("target_savings_progress_dashboard")
    object EditTargetSafe: Routes("edit_target_safe")
    object EditTargetSafeChangeSavingsPlan: Routes("edit_target_safe_change_savings_plan")
    object EditTargetSafeChangeYourTarget: Routes("edit_target_safe_change_your_target")
    object SafeHistory: Routes("safe_history")
    object BreakSafe: Routes("break_safe")
    object TargetSavingsSettingsChangeSuccessful: Routes("changed_target_savings_settings")
    object TargetSavingsTopUpSuccessful: Routes("target_savings_top_up_successful")
    object TargetSavingsWithdrawal: Routes("target_savings_withdrawal")
    object WithdrawalOTPVerification: Routes("withdrawal_otp")
    object SavingsWithdrawalCompletedPrompt: Routes("savings_withdrawal_completed_prompt")
    object FixedSavingsOnboarding: Routes("fixed_savings_onboarding")
    object CreateFixedSavings: Routes("create_fixed_savings")
    object FixedSavingsCreationSuccessfulPrompt: Routes("create_fixed_savings_successful")
    object FixedSavingsCreationFailedPrompt: Routes("create_fixed_savings_failed")
    object FixedSavingsProgressDashboard: Routes("fixed_savings_progress_dashboard")
    object PeriodicSavingsOnboarding: Routes("periodic_savings_onboarding")
    object CreatePeriodicSavings: Routes("create_periodic_savings")
    object PeriodicSavingsCreationSuccessfulPrompt: Routes("periodic_savings_creation_successful")
    //object TakeASelfie1: Routes("take_a_selfie_1")
    //object TakeASelfie2: Routes("take_a_selfie_2")
    //object TakeASelfie1UpdateProfile: Routes("take_a_selfie_1_update_profile")
    //object TakeASelfie2UpdateProfile: Routes("take_a_selfie_2_update_profile")
    // object TakeASelfie3: Routes("take_a_selfie_3")
    //object CapturedImage: Routes("captured_images")
    //object CapturedImageUpdateProfile: Routes("captured_images_update_profile")
    object KegowApp: Routes(route = "kegow_app")
    object ReusableSuccessfulTransaction: Routes(route = "ReusableSuccessfulTransaction")
    object DialogScreen: Routes(route = "dialog_screen")
    object TransactionsHistory: Routes(route = "transactions_history")
    object FundWallet:Routes("fund_wallet")
    object BankTransferReceipt: Routes("bank_transfer_receipt")
    object KegowTransferReceipt: Routes("kegow_transfer_receipt")
    object AirtimeReceipt: Routes("airtime_receipt")
    object CardRequestReceipt: Routes("Card Request Receipt")
    object ElectricityReceipt: Routes("electricity_receipt")
    object CableReceipt: Routes("cable_receipt")
    object TransactionPIN: Routes("transaction_pin")
    object SetTransactionPIN: Routes("set_transaction_pin")
    object OTP: Routes("otp")
    object OTPSignUp: Routes("otp_sign_up")
    object DeviceChangeOTP: Routes("DeviceChangeOTP")
    object KegowTransferSuccessful: Routes("kegow_transfer_successful")
    object WebView: Routes("web_view")
    object TransactionPINSettings: Routes("transaction_pin_settings")
    object ChangeTransactionPinVerifyOTPScreen: Routes("change_transaction_pin_verify_otp_screen")
    object UpdateTransactionPin: Routes("update_transaction_pin")
    object ConfirmUpdateTransactionPin: Routes("confirm_transaction_pin")
    object ConfirmTransactionPinCreation: Routes("confirm_transaction_pin_creation")
    object CreateTransactionPin: Routes("create_transaction_pin")
    object ChangeTransactionPinSuccessful: Routes("change_transaction_pin_successful")
    object CreateTransactionPinSuccessful: Routes("create_transaction_pin_successful")
    object ResetLoginPinValidateUserScreen: Routes("reset_login_pin_validate_user_screen")
    object RevampedCreateAccount: Routes("revamped_create_user_screen")
    object ResetLoginPinSuccessful: Routes("reset_login_pin_successful")
    object ConfirmResetLoginPin : Routes(route = "confirm_reset_login_pin")
    object Spectranet : Routes(route = "spectranet")
    object ChangePinInputOTP : Routes(route = "change_pin_input_otp")
    object CameraPreview: Routes("camera_preview")
    object DisplayQRCode: Routes("display_qr_code")
    object QRCodeTransfer: Routes("qr_code_transfer")
    object QRCodeScannerScreen: Routes("qr_code_scanner_screen")
    object BVNVerify: Routes("verify_bvn")
    object NINVerify: Routes("verify_nin")
    object TermsAndConditionPdfReader: Routes("terms_and_condition_pdf_reader")
    object UserAddress: Routes("user_address")
    object UpdateUserAddress: Routes("update_user_address")
    object CardHomeDeliveryDetails: Routes("card_home_delivery_details")
    object ConfirmCardHomeDeliveryDetails: Routes("confirm_card_home_delivery_details")
    object VerifyNewEmailOTP: Routes("verify_new_email_otp")
    object CardInTransit: Routes("card_in_transit")
    object ActivateCard: Routes("activate_card")
    object ConfirmCardActivationDetails: Routes("confirm_activate_card_details")
    object SelectVerificationChannel: Routes("select_verification_channel")
    object CardManagementDashboard: Routes("card_management_dashboard")
    object ManageCardPIN: Routes("manage_card_pin")
    object ViewCardPIN: Routes("view_card_pin")
    object DeactivateCardHomePage: Routes("deactivate_card_homepage")
    object DeactivateCard: Routes("deactivate_card_screen")
    object SmartLockersLocations: Routes("smart_lockers_locations_map")
    object SelectSmartLockerLocation: Routes("select_smart_lockers_location")
    object SmartLockerCreateParcel: Routes("smart_lockers_create_parcel")
    object SelectSmartLockerCity: Routes("select_smart_lockers_city")
    object Map: Routes("Map")
    object CardPickup: Routes("card_pickup")
    object CardHomeDeliveryAddress: Routes("card_home_delivery_address")
    object CardHomeDeliveryAgent: Routes("card_home_delivery_agent")

}
